config/routes.rb
Rails.application.routes.draw do
  resources :reviews
  resources :cities do
    resources :hotels
  end
  resources :reservations
  resources :guests
  resources :hotels


  get '/signin', to: 'sessions#new'
  post '/signin', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  post '/reservations/new', to: 'reservations#new'
  post '/reviews/new', to: 'reviews#new'

  post '/reservations/:id/edit', to: 'reservations#edit'

  root :to => 'guests#welcome'

  post '/guests/payment', :to => 'guests#payment'

  # patch '/reservation', to: 'reservations#new', as: 'reservation'
end

app/models/guest.rb
require 'active_support/time'
class Guest < ApplicationRecord
  has_many :reservations
  has_many :hotels, through: :reservations


  validates :name, presence: true
  validates :email, uniqueness: true
  validates_confirmation_of :password

  validates :cc_type, presence: true, on: :update
  validates :membership_type, presence: true, on: :update
  validates :credit_card, length: { is: 16 }, on: :update
  validates :cc_exp_date, presence: true, on: :update
  validates :cc_ccv_code, length: { is: 3 }, on: :update

  validates :name_on_card, presence: true, on: :update


  has_secure_password


  # def list_hotel_info(reservation_info)
  #   a=array.each { |id| Hotel.find_by_id(id: id) }
  # end

  def reservation_info
    a=reservations.map { |rsvp| rsvp.hotel_id }
  end

  def reservations
    a=Reservation.all.select { |rsvp| rsvp.guest_id == self.id }
  end

  def membership_plan
    self.membership_type.split(":").first
  end

  def joined_as_member
    self.created_at.strftime("%F").split("-").rotate.join('/')
  end







end

app/controllers/guests_controller.rb
require 'active_support/time'
class GuestsController < ApplicationController
  before_action :require_login, except: [:new, :create, :welcome]



  def welcome
  end

  def index
    @guests = Guest.all
  end

  def show
    # if session[:response]
    #   @hotel = Hotel.find_by_id(id: session[:response])
    #   session.delete(:response)
    # end
    @guest = Guest.find(params[:id])
    @num = @guest.reservation_info
    @reservations = @guest.reservations

    # session[:hotel_rsvps] = @guest.reservation_info
  end



  def new
    @guest = Guest.new
  end

  def create
    @guest = Guest.new(guest_params)
    if @guest.save
      session[:guest_id] = @guest.id
      render :payment
    else
      render :new
    end
  end

   def payment
   end

  def edit
    @guest = Guest.find(params[:id])
  end

  def update
    @guest = Guest.find(session[:guest_id])
    @guest.update(payment_params)
    if @guest.save
        flash[:success] = "Welcome "
        redirect_to @guest
      else
        render :payment
      end
  end

  private

  # def require_login
  #   return head(:forbidden) unless session.include? :guest_id
  # end

  def guest_params
    params.require(:guest).permit(:name, :email, :password, :password_confirmation)
  end

  def payment_params
    params.require(:guest).permit(:membership_type, :cc_type, :name_on_card, :cc_ccv_code, :credit_card, :cc_exp_date)
  end

  def guest_update_params
    params.require(:guest).permit(:name, :email, :password, :password_confirmation, :name_on_card, :cc_ccv_code, :credit_card, :cc_exp_date)
  end

end

app/helpers/guests_helper.rb
module GuestsHelper
end

app/views/guests/_form.html.erb
<%= form_for(@guest) do |f| %>
<a href="http://www.merchantequip.com/information-center/credit-card-logos/"><img
            src="https://www.merchantequip.com/images/logos/visa-mc-amex-184x38.gif" width="184" height="38"
            alt="Merchant Equipment Store Credit Card Logos"/></a>

<br>
<br>
<br>
  <% if @guest.errors.any? %>
    <ul>
      <% @guest.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  <% end %>

<p>Select Your Monthly Plan</p>
<%= f.select :membership_type, options_for_select([["Silver: $50/month "], ["Gold: $90/month"], ["Platinum: $200/month"]]) %>

</br>
</br>
<p>Credit Card Type</p>
<%= f.select :cc_type, options_for_select([["Visa"], ["MasterCard"], ["Amex"]]) %>

</br>
</br>

  <%= f.label :credit_card, 'Credit Card Number: ' %> <br>
  <%= f.text_field :credit_card %>

</br>
</br>

  <%= f.label :cc_exp_date, 'Expiration Date (MM/YY): ' %> <br>
  <%= f.text_field :cc_exp_date %>

</br>
</br>


  <%= f.label :cc_ccv_code, 'CCV code: ' %> <br>
  <%= f.text_field :cc_ccv_code %>

</br>
</br>

  <%= f.label :name_on_card, 'Name on Card: ' %> <br>
  <%= f.text_field :name_on_card %>

</br>
</br>


  <%= f.submit "Make Payment" %><br><br>



  <%= link_to "Already A User? Sign In Here!", signin_path %>

<% end %>

app/views/guests/new.html.erb
<h1> New Guest </h1><br>


<%= form_for(@guest) do |f| %>


<% if @guest.errors.any? %>
<ul>
  <% @guest.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
  <% end %>
</ul>
<% end %>


  <%= f.label :name, 'Full Name: ' %>
  <%= f.text_field :name %>

</br>
</br>

  <%= f.label :email, 'Email: ' %>
  <%= f.text_field :email %>

</br>
</br>

  <%= f.label :password, 'Password: ' %>
  <%= f.password_field :password, autocomplete: "off",
    placeholder: raw("&bull;")%>

</br>
</br>

  <%= f.label :password_confirmation, 'Confirm Password: '  %>
  <%= f.password_field :password_confirmation, autocomplete: "off",
    placeholder: raw("&bull;")%>

</br>
</br>

  <%= f.submit "Sign up" %><br><br>

  <%= link_to "Already A User? Sign In Here!", signin_path %>

<% end %>

app/views/guests/payment.html.erb
<%= render 'form' %>

app/views/guests/show.html.erb
<!-- Greeting -->

<% if flash[:success].present? %>
      <h2><%= flash[:success] %><%=@guest.name.capitalize%>!</h2>
      <% else %>
      <h2><b>Nice to see you, <%=@guest.name.capitalize%>.</b><h2>
  <% end %>

<!-- Guest membership type -->
<% if @reservations.empty? %>
  <% if @guest.membership_type %>
    <h3>Joined <%=@guest.joined_as_member%></h3>
    <h3>Current Plan: <%= @guest.membership_plan %> Membership</h3>
  <% end %>

<a href="/hotels" class="btn btn-lg" style="background-color:#93FFE8; color:#000000; border:1px solid black">Book a hotel</a>

  <hr>



<!-- List guest's reservations -->
<% else !@reservations.empty?  %>
  <% if @guest.membership_type %>
    <h3>Joined <%=@guest.joined_as_member%></h3>
    <h3>Current Plan: <%= @guest.membership_plan %> Membership</h3>
  <% end %>

<a href="/hotels" class="btn btn-lg" style="background-color:#93FFE8; color:#000000; border:1px solid black">Book a hotel</a>

<hr>

<h3>Here's a snapshot of your upcoming trips and trip history... </h3>


<!-- check if upcoming trip or past trip -->
      <% @reservations.each do |rsvp| %>
          <% if rsvp.start > DateTime.now %>

<!-- here are the upcoming trips; guest can edit reservation -->
          <h3>Upcoming Trips <span class="glyphicon glyphicon-ok"></span></h3>
            <div class="reservation">
            <p>Hotel: <%= rsvp.hotel.name %></p>
            <p>City: <%= rsvp.hotel.city.name %></p>

            <p>Check-in Date: <%= rsvp.start.to_date%></p>
            <p>Check-Out Date: <%= rsvp.end.to_date%></p>

              <%= form_tag edit_reservation_path(rsvp) do %>
                <%= hidden_field_tag :reservation_id, rsvp.id %>
                <input class="button" type="submit" value="Edit your reservation">
              <% end %>
            </div>

            <% else %>
          <h3>Past Trips <span class="glyphicon glyphicon-ok"></span></h3>
              <div class="reservation">
              <p>Hotel: <%= rsvp.hotel.name %></p>
              <p>City: <%= rsvp.hotel.city.name %></p>

              <p>Check-in Date: <%= rsvp.start.to_date%></p>
              <p>Check-Out Date: <%= rsvp.end.to_date%></p>
                <%= form_tag new_review_path do %>
                  <%= hidden_field_tag :reservation_id, rsvp.id %>
                  <input class="button" type="submit" value="Review this hotel">
                <% end %>
                </div>
            <% end%>
          <% end %>



    <% end %>

app/views/guests/welcome.html.erb
<div class="welcome_pg">
<%= image_tag("Conde_nast.jpg", size: "1000x500") %>
</div>



<div class="welcome_pg">
<h1><b>Hey, you! <span class="glyphicon glyphicon-glass"></span></b></h1>
<p><i>We know you like to stay in style when you travel.<br>
Now you can--and at an affordable price--with Suite Spot.</i></p>
<h3><%=link_to "Sign Up", new_guest_path%> | <%=link_to "Sign In", signin_path%></h3>

<body>

<div class="container1">

<div class="first" >
  <div class="card-body">
    <h4 class="card-title"><b>Silver Membership</b></h4>
    <p class="card-text">
      For occasional travelers<br>
      1 Credit<br>
      $50 per month
      </p>
     <a href=/guests/new class="btn btn" style="background-color:#93FFE8; color:#000000; border:1px solid black;"><b>Select Plan</b></a>
  </div>
</div>

<div class="second" >
  <div class="card-body">
    <h4 class="card-title"><b>Gold Membership</b></h4>
    <p class="card-text">
      Our most popular plan for regular travelers<br>
      2 Credits<br>
      $90 per month<br>
    <a href=/guests/new class="btn btn" style="background-color:#93FFE8; color:#000000; border:1px solid black;"><b>Select Plan</b></a>
  </div>
</div>

<div class="third" >
  <div class="card-body">
    <h4 class="card-title"><b>Platinum Membership</b></h4>
    <p class="card-text">
      Premium plan with access to executive lounges<br>
      5 Credits<br>
      $200 per month<br>
    </p>
    <a href=/guests/new class="btn btn" style="background-color:#93FFE8; color:#000000; border:1px solid black"><b>Select Plan</b></a>
  </div>
</div>

</div>


</body>

</div>