config/routes.rb
Rails.application.routes.draw do
  resources :reviews
  resources :cities do
    resources :hotels
  end
  resources :reservations
  resources :guests
  resources :hotels


  get '/signin', to: 'sessions#new'
  post '/signin', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  post '/reservations/new', to: 'reservations#new'
  post '/reviews/new', to: 'reviews#new'

  post '/reservations/:id/edit', to: 'reservations#edit'

  root :to => 'guests#welcome'

  post '/guests/payment', :to => 'guests#payment'

  # patch '/reservation', to: 'reservations#new', as: 'reservation'
end

app/models/city.rb
class City < ApplicationRecord
  has_many :hotels


  # def hotel_names
  #   city_hotels.map { |hotel| hotel.name }

  # end

  # def hotel_id
  #   city_hotels.map { |hotel| hotel.id }
  # end

  # def city_hotels
  #   a = Hotel.all.select { |h| h.city_id == self.id }
  # end



end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController

    def index
        @cities = City.all
    end

    def show
        @city = City.find(params[:id])
        @hotels = @city.hotels
        @cities = City.all
    end

end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/views/cities/show.html.erb
<div class="center_align">

<h2><%= @city.name %><br><br>
  <span class="glyphicon glyphicon-map-marker"</span></h2>

  <% @hotels.each do |hotel| %>

      <p><%= link_to hotel.name,  city_hotel_path(@city, hotel)%></p>

  <% end %>


<% @cities.find do |city| %>
  <% if city = @city%>
    <img src="/assets/<%=city.image_url%>">
  <% end %>
<% end %>

</div>