config/routes.rb
Rails.application.routes.draw do
  resources :reviews
  resources :cities do
    resources :hotels
  end
  resources :reservations
  resources :guests
  resources :hotels


  get '/signin', to: 'sessions#new'
  post '/signin', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  post '/reservations/new', to: 'reservations#new'
  post '/reviews/new', to: 'reviews#new'

  post '/reservations/:id/edit', to: 'reservations#edit'

  root :to => 'guests#welcome'

  post '/guests/payment', :to => 'guests#payment'

  # patch '/reservation', to: 'reservations#new', as: 'reservation'
end

app/models/hotel.rb
class Hotel < ApplicationRecord
  has_many :reservations
  has_many :guests, through: :reservations
  belongs_to :city
  has_many :reviews, through: :reservations

  def post_reviews_on_hotel_show_page
    @hotel = Hotel.find(params[:id])
    @reviews = Review.all
    @all_reviews_for_this_hotel = hotel.reservations.collect do |reservation|
      reservation.reviews
    end
    flattened = @all_reviews_for_this_hotel.flatten
    @all_titles = flattened.each do |r|
      r[:title]
    end
    all_content = flattened.collect do |r|
      r[:content]
    end
    all_titles
  end

  # def reviews
  #   Review.all.select { |rev| rev.reservation_id == }
  # end




end

app/controllers/hotels_controller.rb
class HotelsController < ApplicationController
  before_action :require_login

  def index
    @hotels = Hotel.all
  end

  def show
    @hotel = Hotel.find(params[:id])
    @reviews = Review.all
    @all_reviews_for_this_hotel = @hotel.reservations.collect do |reservation|
      reservation.reviews
    end
    flattened = @all_reviews_for_this_hotel.flatten
    @all_content = flattened.collect do |r|
      r[:content]
    end
  end

end

app/helpers/hotels_helper.rb
module HotelsHelper
end

app/views/hotels/index.html.erb
<h2> Check out all our partner hotels... </h2>

<% @hotels.each do |hotel| %>

<div id="hotel_profile_pics">

<div class="container1">
<img src="/assets/<%=hotel.profile_img%>" >
  <div class="hotel_index">
    <h4 class="card-title"><%=hotel.name %></h4>
    <p class="card-text"><%=hotel.description %></p>
    <a href="/hotels/<%=hotel.id%>" class="btn btn-lg btn-block" style="background-color:#93FFE8; color:#000000; border:1px solid black">More info </a>

  </div>
</div>


<br>
<hr>
</div>



<% end %>

app/views/hotels/new.html.erb
<%= simple_form_for @hotel :html => { :multipart => true } do |f| %>
    <%= select_tag :city_id, options_for_select(@cities), prompt => "Select a City") %>
    <%= f.input :name, label: "Hotel Name" %>
    <%= f.input :description %>
    <%= f.input :address %>
    <%= f.input :tel %>
    <%= f.button :submit %>


<% end %>

app/views/hotels/show.html.erb
<div class="col-xs-6">
  <div class="hotel_show_page">

    <h2><b><%= @hotel.name %></b></h2>
    <h3><%= @hotel.city.name  %><span class="glyphicon glyphicon-map-marker"></span></h3><br>
      <div id="myDiv">
        <%= image_tag(@hotel.image_url, size: "4.76 x 5.74", :alt => "rss feed", :class => "myDiv") %></br>
      </div><br>


  <%= form_tag new_reservation_path do %>
    <%= hidden_field_tag :hotel_id, @hotel.id %>
    <button type="submit" class="btn btn-lg btn-block" style="background-color:#93FFE8; color:#000000; border:1px solid black">Book this hotel</button>

  <%end %></br>
</div>
</div>

<div class="col-xs-6">

  <h2>Most Recent Reviews... <span class="glyphicon glyphicon-pencil"></span></h2><br>
    <% if !@all_content.empty? %>
      <% @all_content.each do |c| %>
        <font color="gray"><i>"<%= c %>"</i></br></br>
      <% end %>
    <% else %>
      <p><i>Uh oh, we're a little short on reviews for this hotel...</i></p>
    <% end %>




<hr><br>
  <div class="container-fluid" style="background-color:#B6B6B4; border:1px solid black; box-shadow: 10px 10px 5px grey">

    <font color="white">
     <div class="center_align">
        <h1><span class="glyphicon glyphicon-sunglasses"></span>
        <span class="glyphicon glyphicon-sunglasses"></span>
        <span class="glyphicon glyphicon-sunglasses"></span></h1>
      </div>
    <p><%= @hotel.description %></p>
    </br>

    <p><b>Address: </b><%= @hotel.address %></p>
    <p><b>Tel: </b><%= @hotel.tel %></p></font>



</div>